server:
  port: 8080
  servlet:
    context-path: /marking_system
my-props:
  static-path: /Users/JZ/Documents/GitHub/marking_system/src/main/resources/static
  upload-path: /Users/JZ/Downloads/test
spring:
  mvc:
    static-path-pattern: /**
  resources:
      static-locations: file:${my-props.static-path}, file:${my-props.upload-path}
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/marking_system
    username: root
    password: 123
mybatis:
  type-aliases-package: ga.dqrjz.marking.pojo
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true